name: Keep Alive

on:
  schedule:
    - cron: "0,10 * * * *"
  workflow_dispatch:

jobs:
  wake:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          pip install playwright
          playwright install chromium --with-deps

      - name: Wake app
        run: python3 wake.py
